# Generated by Django 5.1.6 on 2025-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_description_alter_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=36),
        ),
    ]
