print ("Section 2")
print (3+4)
print (3-4)
print (3*4)
print (3/4)
print (3**4)
print (3//4)
print ("")
print ("Section 3")
print ("Jeremy")
print ("Barnes")
print ("USA")
print ("I am enjoying 30 days of python")
print ("")
print (type(10))
print (type(9.8))
print (type(3.14))
print (type(4 -4j))
print (type(['Jeremy', 'Python', 'USA']))
print (type("Jeremy"))
print (type("Barnes"))
print (type("USA"))

