# Generated by Django 5.1.6 on 2025-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_book_cover_book_description_book_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(null=True),
        ),
    ]
